// This'll be CouchDB'd in full whack. Temp quick win here.

this.home = [
  '<div id="content">',
  '<h1>Dave Stevens <span>Enthusiast.</span></h1>',
  '<p class="first">',
    'Dave Stevens is a developer who loves JavaScript and all things Mobile. <em>I</em> am Dave Stevens. Currently, I\'m exploring the possibilities of <a href="http://nodejs.org">node.js</a> and getting',
    'very, very excited about what can be achieved. I\'d love to talk to you.',
  '</p>',
  '<h2>Articles</h2>',
  '<ul>',
    '<li class="dev"><a href="/articles/setting-up-node-js-and-couchdb-on-webfaction">Setting up node.js and CouchDB on Webfaction</a> A quick guide to getting set up with node &amp; CouchDB on Webfaction hosting using git and the control panel.</li>',
  '</ul>',
  '<h2>On the subject of writing</h2>',
  '<p>',
    'Like most developers I\'ve ever met, I tend to find there just aren\'t enough hours in the day to achieve everything I\'d like to. As a result, I don\'t intend to maintain',
    'a regular blog here as I would hate for it to become stale &amp; stagnant when time constraints prevented me from writing. However, I do love to write and I have plenty to talk',
    'about, so expect infrequent posts to appear here in something loosely reminiscent of article form.',
  '</p>',
  '<div id="photo"><img src="/imgs/dave.jpg"/><span>I look like this</span></div>',  
  '</div>',
  '<div id="twitter"><a href="http://twitter.com/shakefon">YOU SHOULD FOLLOW ME ON TWITTER.</a></div>'  
].join('\n');

this.aea = [
  '<div id="content">',
  '<h1>Welcome, fellow <span>An Event Apart</span> attendee.</h1>',
  '<p class="first hasPhoto">',
    'I\'m Dave Stevens, a 26 year old web developer who you met at <a href="http://aneventapart.com">An Event Apart</a> in San Diego, CA.  Alternatively, you may have found a business card at the Conference.',
  '</p>',
  '<h2>What\'s with the page?</h2>',
  '<p>',
    'I often meet folks at these events and have every intention of keeping in touch. However, I\'m not all that great at correctly remembering Twitter handles, email addresses or - and this is the worst part - names.',
    'So, I figured this time round I would do things right and pass out business cards with a unique URL on them, bringing anyone I interacted with to this page. Thanks for being one of them!',
  '</p>',
  '<h2>So who are you again?</h2>',
  '<p>',
    'I\'m Dave Stevens. I\'m from a little place called England, but I now call sunny Las Vegas, Nevada my home. By day, I\'m a Front-End Developer at <a href="http://www.zappos.com">Zappos</a>. By night, being utterly devoid of crime-fighting skills, I spend much of my time getting to grips with and thoroughly adoring <a href="http://nodejs.org">node.js</a>.',
    'The majority of my time is spent working in Javascript, though through the course of a career that has included a strong mobile background, I have made heavy use of HTML, CSS, PHP, a little .NET and JSP in full-time employment for Microsoft, ESPN and on a freelance basis for a multitude of varied customers.', 
  '</p>',
  '<h2>And how might we contact you?</h2>',
  '<p>',
    'I like receiving <a href="mailto:davestevens84@gmail.com">e-mail [davestevens84@gmail.com]</a>, check <a href="http://twitter.com/shakefon">Twitter [@shakefon]</a> more often than I probably should and can be found on Skype (developerdave).',
    'If you have another web service you prefer to use, chances are if I\'m on there you\'ll find me under the username "shakefon".',
  '</p>',
  '<h2>But why exactly SHOULD we contact you?</h2>',
  '<p>',
    'Well, I\'m not one for telling people to do things. I\'d hope that maybe you wanted to continue a discussion we started at AEA, or perhaps you\'ve got an idea you want to get off the ground and maybe I might be someone who could help you with that. Maybe you just love node.js and finding anyone else who does is reason alone. I really don\'t mind why you would choose to contact me, but I welcome your message.',
  '</p>',
  '<div id="photo"><img src="/imgs/dave.jpg"/><span>I look like this</span></div>',  
  '</div>',
  '<div id="twitter"><a href="http://twitter.com/shakefon">YOU SHOULD FOLLOW ME ON TWITTER.</a></div>'
].join('');
